SELECT CAR_ID,CAR_TYPE, FEE
FROM (
    SELECT B.CAR_ID, B.CAR_TYPE, ROUND((B.DAILY_FEE*(100-A.DISCOUNT_RATE)*0.01*30),0) AS FEE
    FROM (
        SELECT CAR_TYPE,DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE DURATION_TYPE='30일 이상' AND (CAR_TYPE='세단' OR CAR_TYPE='SUV')) AS A
    JOIN (
        SELECT CAR_RENTAL_COMPANY_CAR.CAR_ID, CAR_TYPE, DAILY_FEE
        FROM CAR_RENTAL_COMPANY_CAR LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY
        ON CAR_RENTAL_COMPANY_CAR.CAR_ID=CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
        WHERE (CAR_TYPE = 'SUV' OR CAR_TYPE = '세단') 
        AND (CAR_RENTAL_COMPANY_RENTAL_HISTORY.END_DATE < '2022-11-01' 
            OR CAR_RENTAL_COMPANY_RENTAL_HISTORY.START_DATE > '2022-11-30')
        GROUP BY CAR_RENTAL_COMPANY_CAR.CAR_ID
        ORDER BY CAR_ID DESC) AS B
    ON A.CAR_TYPE=B.CAR_TYPE) AS C
WHERE 500000 <= FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;