SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.ANIMAL_TYPE, ANIMAL_OUTS.NAME
FROM ANIMAL_INS JOIN ANIMAL_OUTS
ON ANIMAL_INS.ANIMAL_ID=ANIMAL_OUTS.ANIMAL_ID
WHERE LEFT(SEX_UPON_INTAKE,6)='Intact' AND LEFT(SEX_UPON_OUTCOME,6)!='Intact';