SELECT FOOD_PRODUCT.PRODUCT_ID,PRODUCT_NAME,(B.AMOUNT*FOOD_PRODUCT.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM (
        SELECT *
        FROM FOOD_ORDER
        WHERE MONTH(PRODUCE_DATE)=5) AS A
    GROUP BY PRODUCT_ID) AS B
ON FOOD_PRODUCT.PRODUCT_ID=B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;