SELECT B.FLAVOR
FROM (
    SELECT FIRST_HALF.FLAVOR, (FIRST_HALF.TOTAL_ORDER+A.TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF JOIN (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM JULY
        GROUP BY FLAVOR) AS A
    ON FIRST_HALF.FLAVOR=A.FLAVOR
    GROUP BY FIRST_HALF.FLAVOR
    ORDER BY TOTAL_ORDER DESC) AS B
LIMIT 3;