SELECT B.APNT_NO, PATIENT.PT_NAME, B.PT_NO, B.MCDP_CD, B.DR_NAME, B.APNT_YMD
FROM PATIENT JOIN (
    SELECT A.APNT_NO, A.PT_NO, A.MCDP_CD, DOCTOR.DR_NAME, A.APNT_YMD
    FROM DOCTOR JOIN (
        SELECT APNT_NO, MDDR_ID, PT_NO, MCDP_CD, APNT_YMD
        FROM APPOINTMENT
        WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13' AND APNT_CNCL_YN='N' AND MCDP_CD='CS') AS A
    ON DOCTOR.DR_ID=A.MDDR_ID) AS B
ON PATIENT.PT_NO=B.PT_NO
ORDER BY APNT_YMD ASC;