SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE JOIN (
    SELECT A.MEMBER_ID, REVIEW_TEXT, REVIEW_DATE
    FROM REST_REVIEW JOIN (
        SELECT B.MEMBER_ID, B.COUNT
        FROM (
            SELECT MEMBER_ID, COUNT(*) AS COUNT
            FROM REST_REVIEW
            GROUP BY MEMBER_ID) AS B
        WHERE B.COUNT=(
            SELECT MAX(COUNT) 
            FROM (
                SELECT MEMBER_ID, COUNT(*) AS COUNT
                FROM REST_REVIEW
                GROUP BY MEMBER_ID) AS A)) AS A
    ON A.MEMBER_ID=REST_REVIEW.MEMBER_ID) AS D
ON D.MEMBER_ID=MEMBER_PROFILE.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;