SELECT SUM(A.COUNT) AS FISH_COUNT
FROM FISH_NAME_INFO
JOIN (
    SELECT FISH_TYPE, COUNT(*) AS COUNT
    FROM FISH_INFO
    GROUP BY FISH_TYPE) AS A
ON FISH_NAME_INFO.FISH_TYPE=A.FISH_TYPE
WHERE FISH_NAME_INFO.FISH_NAME IN ('BASS', 'SNAPPER')