SELECT DISTINCT CAR_RENTAL_COMPANY_CAR.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE)=10) AS A
ON CAR_RENTAL_COMPANY_CAR.CAR_ID=A.CAR_ID
WHERE CAR_TYPE='세단'
ORDER BY CAR_ID DESC;